name: Rust

on:
  push:
    branches: [ "signal" ]
  pull_request:
    branches: [ "signal" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update
      run: cargo update -p half@2.4.1 --precise 2.2.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
